window.GROWTH_OS_DATA = {
  assetTypes: [
    { id: "database", name: "数据库" },
    { id: "sop", name: "SOP" },
    { id: "rule", name: "规律" },
    { id: "risk", name: "风险" },
    { id: "case", name: "案例" },
    { id: "script", name: "话术" },
    { id: "ai", name: "AI知识" }
  ],
  projects: [
    { id: "new-media-growth", title: "医美新媒体成长", url: "projects/new-media-growth.html", status: "进行中", tags: ["主线项目", "运营", "转化"] },
    { id: "ai-workflow", title: "AI工作流项目", url: "projects/ai-workflow.html", status: "进行中", tags: ["主线项目", "AI", "自动化"] },
    { id: "growth-lab", title: "网站项目", url: "projects/ajian-growth-lab.html", status: "进行中", tags: ["主线项目", "Growth OS", "网站"] },
    { id: "life-rules", title: "人生规律库", url: "projects/life-rules.html", status: "长期沉淀", tags: ["主线项目", "规律", "判断系统"] },
    { id: "cognition-library", title: "认知库", url: "projects/cognition-library.html", status: "长期沉淀", tags: ["主线项目", "认知", "思维模型"] },
    { id: "video-benchmark", title: "视频数据库", url: "projects/video-benchmark.html", status: "进行中", tags: ["子库", "医美新媒体成长", "数据"] },
    { id: "lead-sop", title: "引流SOP", url: "knowledge.html", status: "待沉淀", tags: ["子库", "医美新媒体成长", "SOP"] },
    { id: "comment-sop", title: "评论SOP", url: "knowledge.html", status: "待沉淀", tags: ["子库", "医美新媒体成长", "SOP"] },
    { id: "operation-risk-library", title: "风险库", url: "knowledge.html", status: "持续更新", tags: ["子库", "医美新媒体成长", "风险"] },
    { id: "account-cold-start", title: "新人培训", url: "projects/account-cold-start.html", status: "20%", tags: ["子库", "医美新媒体成长", "培训"] },
    { id: "operation-ai-workflow", title: "AI工作流（运营版）", url: "projects/ai-workflow.html", status: "进行中", tags: ["子库", "医美新媒体成长", "AI"] },
    { id: "operation-results", title: "项目成果", url: "knowledge.html", status: "持续更新", tags: ["子库", "医美新媒体成长", "成果"] },
    { id: "ocr-workflow", title: "OCR工作流", url: "knowledge.html", status: "待沉淀", tags: ["子库", "AI工作流项目", "OCR"] },
    { id: "video-automation", title: "视频数据库自动化", url: "projects/video-benchmark.html", status: "规划中", tags: ["子库", "AI工作流项目", "自动化"] },
    { id: "handoff-generator", title: "项目交接卡生成", url: "handoffs.html", status: "运行中", tags: ["子库", "AI工作流项目", "交接卡"] },
    { id: "whitepaper-generator", title: "白皮书生成", url: "whitepapers.html", status: "运行中", tags: ["子库", "AI工作流项目", "白皮书"] },
    { id: "site-update-workflow", title: "网站更新工作流", url: "projects/ajian-growth-lab.html", status: "运行中", tags: ["子库", "AI工作流项目", "网站"] },
    { id: "cross-industry-ai-workflow", title: "其他行业AI工作流", url: "knowledge.html", status: "规划中", tags: ["子库", "AI工作流项目", "行业迁移"] }
  ],
  assets: [
    {
      id: "rule-life-first",
      title: "生命第一",
      type: "rule",
      date: "2026-07-22",
      summary: "生命、健康和安全是所有成长、收入、项目和长期规划的前提。",
      content: "有生命才有其他的东西。健康、安全和基本生存状态，是成长、收入、项目、机会、关系和长期规划的前提。",
      projects: ["life-rules", "new-media-growth"],
      tags: ["生命", "健康", "底层原则"],
      status: "已沉淀",
      createdAt: "2026-07-22",
      updatedAt: "2026-07-22"
    },
    {
      id: "sop-account-cold-start",
      title: "账号冷启动 SOP 雏形",
      type: "sop",
      date: "2026-07-22",
      summary: "账号从 0 到 1 需要先完成定位、资料、测试、互动和数据观察。",
      content: "账号从 0 到 1 需要先完成定位、基础资料、内容测试、评论互动和初始数据观察，再把有效动作整理成新人可执行清单。",
      projects: ["account-cold-start", "new-media-growth"],
      tags: ["账号冷启动", "SOP", "新人培训"],
      status: "草稿",
      createdAt: "2026-07-22",
      updatedAt: "2026-07-22"
    },
    {
      id: "case-operation-544",
      title: "运营案例 544+ 持续沉淀",
      type: "case",
      date: "2026-07-22",
      summary: "把引流、评论沟通、转化反馈和风控问题沉淀为长期案例库。",
      content: "把引流、评论沟通、转化反馈和风控问题作为长期案例库沉淀，后续用于总结可复用运营规律。",
      projects: ["new-media-growth"],
      tags: ["运营案例", "引流", "转化"],
      status: "持续更新",
      createdAt: "2026-07-22",
      updatedAt: "2026-07-22"
    },
    {
      id: "risk-vpn-stability",
      title: "VPN 稳定性影响工具链",
      type: "risk",
      date: "2026-07-22",
      summary: "VPN 稳定性会影响谷歌商店、GPT 文件下载、资料访问和 AI 工作流连续性。",
      content: "VPN 稳定性不只影响谷歌商店下载，也会影响 GPT 生成文件下载、资料访问和 AI 工作流连续性。",
      projects: ["ai-workflow", "growth-lab"],
      tags: ["VPN", "稳定性", "下载"],
      status: "已记录",
      createdAt: "2026-07-22",
      updatedAt: "2026-07-22"
    },
    {
      id: "rule-eye-rest",
      title: "眼部恢复规则",
      type: "rule",
      date: "2026-07-22",
      summary: "凌晨 12 点半前睡觉，不在无光环境下玩手机，减少眼睛疲劳。",
      content: "每天尽量凌晨 12 点半前睡觉，晚上不要在无光情况下玩手机，减少第二天眼睛疲劳和精力下滑。",
      projects: ["life-rules"],
      tags: ["眼睛", "睡眠", "健康"],
      status: "已沉淀",
      createdAt: "2026-07-22",
      updatedAt: "2026-07-22"
    },
    {
      id: "ai-codex-site-flow",
      title: "Codex 更新网站工作流",
      type: "ai",
      date: "2026-07-20",
      summary: "复盘后生成交接卡和白皮书，再由 Codex 更新网站，形成连续协作流程。",
      content: "每天复盘后生成项目交接卡和成长白皮书，再由 Codex 更新网站，形成“记录-沉淀-发布”的连续协作流程。",
      projects: ["growth-lab", "ai-workflow"],
      tags: ["Codex", "网站更新", "AI协作"],
      status: "运行中",
      createdAt: "2026-07-20",
      updatedAt: "2026-07-22"
    },
    {
      id: "sop-lead-risk-control-2026-07-23",
      title: "引流账号风控 SOP",
      type: "sop",
      date: "2026-07-23",
      summary: "普通账号直接私信、频繁关注和固定话术都容易触发风控，需要控制频率、轮换动作和避免高风险词。",
      content: "普通引流账号不要频繁直接私信，每天建议只私信 1-2 个；账号引流次数较少时慎用“了解”等容易触发风控的词；关注客户要轮换节奏，避免短时间大量关注导致禁止关注或弹验证。",
      projects: ["new-media-growth", "lead-sop", "operation-risk-library"],
      tags: ["引流SOP", "风控", "私信", "关注频率", "抖音"],
      status: "已沉淀",
      createdAt: "2026-07-23",
      updatedAt: "2026-07-23"
    },
    {
      id: "sop-blue-v-carrying-2026-07-23",
      title: "蓝V账号承接 SOP",
      type: "sop",
      date: "2026-07-23",
      summary: "蓝V账号权重更高，适合承接更多私信，但历史异常账号仍可能持续触发风控。",
      content: "蓝V账号权重通常高于普通账号，每天可承接更多私信；每个人可验证多个蓝V账号。但如果某个蓝V账号之前出现过关注、私信或风控问题，后续仍可能频繁异常，需要单独记录和隔离。",
      projects: ["new-media-growth", "lead-sop", "operation-risk-library"],
      tags: ["蓝V", "承接", "私信", "风控", "引流SOP"],
      status: "已沉淀",
      createdAt: "2026-07-23",
      updatedAt: "2026-07-23"
    },
    {
      id: "sop-comment-attract-attention-2026-07-23",
      title: "评论引流基础动作 SOP",
      type: "sop",
      date: "2026-07-23",
      summary: "评论引流的核心是引起对方注意并降低信任成本，而不是在评论区完成完整沟通。",
      content: "引流动作可先对目标账号作品做随机点赞和收藏，再评论一句低压提示，如“你好美女，看你在我大号下面评论了，那边回不了你，这边回关一下。”评论后关注对方，等待回关，不要继续做多余动作。",
      projects: ["new-media-growth", "comment-sop", "lead-sop"],
      tags: ["评论SOP", "引流", "回关", "信任成本"],
      status: "已沉淀",
      createdAt: "2026-07-23",
      updatedAt: "2026-07-23"
    },
    {
      id: "script-lead-v1-v2-2026-07-23",
      title: "引流话术 V1/V2 迭代",
      type: "script",
      date: "2026-07-23",
      summary: "话术不是固定模板，核心目标是先建立信任，再自然引导到微信。",
      content: "第一版：回关后先打招呼，再问“请问想了解什么”，再承接“之前做过吗”“还有什么想了解的”，最后说明这里聊不了太专业并引导留号。第二版：更重视观察对方作品和状态，减少无效长聊，用“最近粉丝比较多，这里可能比较忙，看不到”降低转移阻力。最终原则是持续调整，找到适合自己的话术。",
      projects: ["new-media-growth", "comment-sop", "lead-sop"],
      tags: ["话术", "引流", "加V", "信任", "转化"],
      status: "已沉淀",
      createdAt: "2026-07-23",
      updatedAt: "2026-07-23"
    },
    {
      id: "risk-comment-script-decay-2026-07-23",
      title: "话术失效与评论被吞风险",
      type: "risk",
      date: "2026-07-23",
      summary: "固定话术和引导性表情包会被平台识别，导致评论不显示或被吞。",
      content: "话术需要隔段时间变化。大量重复同一句话、使用带明显引导性质的表情包或在同类场景里高频操作，都可能导致评论区不显示、被吞或触发风控。",
      projects: ["new-media-growth", "comment-sop", "operation-risk-library"],
      tags: ["评论被吞", "话术失效", "表情包", "风控"],
      status: "已沉淀",
      createdAt: "2026-07-23",
      updatedAt: "2026-07-23"
    },
    {
      id: "case-lead-conversion-playbook-2026-07-23",
      title: "引流转化流程沉淀",
      type: "case",
      date: "2026-07-23",
      summary: "从关注、评论、回关、私信到加V，形成一套可复盘的引流转化路径。",
      content: "这份文档把账号风控、评论动作、蓝V承接、私信频率、话术迭代和作品违规检查串成一个完整流程，是医美新媒体成长项目里的阶段性项目成果。",
      projects: ["new-media-growth", "operation-results", "lead-sop", "comment-sop"],
      tags: ["项目成果", "引流转化", "流程沉淀", "医美运营"],
      status: "已沉淀",
      createdAt: "2026-07-23",
      updatedAt: "2026-07-23"
    },
    {
      id: "rule-repetition-as-experiment-2026-07-14",
      title: "重复的不是工作，而是实验",
      type: "rule",
      date: "2026-07-14",
      summary: "同样的重复动作，如果持续提出问题、验证假设、沉淀结论，就会变成实验和能力升级。",
      content: "表面上每天都在评论、私信、回复用户，但真正有价值的是追问为什么评论被吞、为什么蓝V和普通账号表现不同、为什么今天有效明天失效，以及如何降低风控和优化引流流程。",
      projects: ["cognition-library", "life-rules", "new-media-growth"],
      tags: ["认知库", "重复工作", "实验思维", "运营"],
      status: "已沉淀",
      createdAt: "2026-07-14",
      updatedAt: "2026-07-23"
    },
    {
      id: "rule-system-thinking-operation-2026-07-14",
      title: "从优化一句评论，到优化整个运营系统",
      type: "rule",
      date: "2026-07-14",
      summary: "运营能力的升级，是从单点动作优化，走向账号、数据库、AI和人工校验组成的系统协作。",
      content: "普通账号负责互动，蓝V负责承接，数据库负责分析，Codex负责重复劳动，人工负责校验。系统思维让经验不再停留在个人手感，而能沉淀成可复用 SOP。",
      projects: ["cognition-library", "new-media-growth", "ai-workflow"],
      tags: ["认知库", "系统思维", "运营SOP", "AI工作流"],
      status: "已沉淀",
      createdAt: "2026-07-14",
      updatedAt: "2026-07-23"
    },
    {
      id: "rule-job-value-scene-2026-07-14",
      title: "岗位提供场景，成长来自方法",
      type: "rule",
      date: "2026-07-14",
      summary: "工作价值不只由岗位决定，而由自己是否持续提出问题、验证假设并沉淀长期能力决定。",
      content: "真正决定一份工作价值的，不是它是否重复，而是自己是否持续提出新的问题、验证新的假设，并把结论沉淀为长期能力。岗位提供的是场景，成长来自在场景里建立起来的方法、系统和思维。",
      projects: ["cognition-library", "life-rules", "new-media-growth"],
      tags: ["认知库", "工作价值", "长期能力", "方法论"],
      status: "已沉淀",
      createdAt: "2026-07-14",
      updatedAt: "2026-07-23"
    }
  ]
};
